name: CI

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  checkers:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clang-format style check (.c and .h)
      uses: jidicula/clang-format-action@master

  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        compiler: [gcc, clang]

    steps:
    - name: Prepare
      run: sudo apt install libevent-dev

    - uses: actions/checkout@v2

    - name: Create build folder
      run: cmake -E make_directory build

    - name: Generate makefiles
      env:
        CC: ${{ matrix.compiler }}
        CXX: ${{ matrix.compiler }}
      # Use a bash shell so we can use the same syntax for environment variable
      # access regardless of the host operating system
      shell: bash
      working-directory: build
      run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DENABLE_SSL=ON ..

    - name: Build
      shell: bash
      working-directory: build
      run: cmake --build . --config $BUILD_TYPE

    # - name: Test
    #   working-directory: build
    #   shell: bash
    #   run: ctest -C $BUILD_TYPE
